apiVersion: v1
kind: Secret
metadata:
  name: bank-backend-secret
type: Opaque
data:
  DB_USERNAME: admin
  DB_PASSWORD: BankApp2025SecurePass!


## echo -n "root" | base64
## echo -n "password123ABC" | base64
